Migrate form yarn to pnpm

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,20 +13,25 @@ jobs:
     steps:
       - uses: actions/checkout@v6
         
+      - uses: pnpm/action-setup@v4
+        with:
+          version: latest
+
       - uses: actions/setup-node@v6
         with:
           node-version: 20
+          cache: 'pnpm'
 
-      - name: "yarn install"
-        run: yarn install
+      - name: "pnpm install"
+        run: pnpm install
       
-      - name: "yarn build"
-        run: yarn build
+      - name: "pnpm build"
+        run: pnpm build
 
       - name: "check for uncommitted changes"
         # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
         run: |
           git diff --exit-code --stat -- . ':!node_modules' \
-          || (echo "##[error] found changed files after build. please 'yarn build && npm run format'" \
+          || (echo "##[error] found changed files after build. please 'pnpm build && pnpm run format'" \
                    "and check in all changes" \
               && exit 1)
